version: 2
sources:
  - name: staging
    database: psychic-medley-376114
    schema: nyc_bus_dataset
    tables:
      - name: bus_records
      - name: temperature
      - name: humidity
      - name: weather_description
